version: 2
updates:
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 5   
    labels:
      - "dependencies"

    # Enable version updates for Docker
#  - package-ecosystem: "docker"
#    # Look for a `Dockerfile` in the `root` directory
#    directory: "/"
    # Check for updates once a week
#    schedule:
#        interval: "weekly"