services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/devoops23b/gosearch:latest
    container_name: go-app
    volumes:
      - ./src/backend:/app/src/backend
      - ./src/whoknows.db:/app/src/gosearch.dev.db
    ports:
      - "8081:8080"
    environment:
      - DATABASE_PATH=/app/src/gosearch.dev.db
      - APP_ENV=development
      - LOG_LEVEL=debug
    restart: always