services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ghcr.io/devoops23b/gosearch:latest
    container_name: go-app
    volumes:
      - ./src/backend:/app/src/backend
      - ./src/whoknows.db:/app/src/gosearch.dev.db
    ports:
      - "8081:8080"
    environment:
      - CONN_STR=host=postgres port=5432 user=youruser password=yourpassword dbname=whoknows sslmode=disable
      - APP_ENV=development
      - LOG_LEVEL=debug
      - ES_HOST=elasticsearch
    depends_on:
      postgres:
        condition: service_started
      elasticsearch:
        condition: service_healthy
    restart: always

  postgres:
    image: postgres:13
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: whoknows
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.5.0
    container_name: elasticsearch
    environment:
      discovery.type: single-node
      ELASTIC_PASSWORD: changeme
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"
      xpack.security.enabled: "false"
      xpack.security.http.ssl.enabled: "false"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  postgres_data:
  esdata: