global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gosearch'
    scheme: https
    tls_config:
      insecure_skip_verify: true
    static_configs:
      - targets: 
          - 'gosearch.dk'
      