global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'gosearch'
    metrics_path: '/metrics'
    scheme: http
    static_configs:
      - targets: 
          - '40.91.244.170:8081'
      