name: Go Gorilla CI Pipeline
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true
      
      - name: Install Dependencies
        run: go mod tidy
      
      - name: Build
        run: go build -v ./...
      
      - name: Run Tests
        run: go test -v -race -p=4 ./...
      
      - name: Verify Dependencies
        run: go mod verify