name: Go CI

on:
  push:
    branches:
      - main
      - Develop
  pull_request:
    branches:
      - main
      - Develop
  workflow_dispatch:    

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
        ports:
          - 9200:9200
        env:
          discovery.type: single-node
          xpack.security.enabled: false
        options: >-
          --health-cmd="curl -f http://localhost:9200/_cluster/health || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Check out code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
        with:
          go-version: 1.21  


      - name: Clean Go cache
        run: |
          go clean -modcache
          rm -rf $GOPATH/pkg/mod
          rm -rf ~/.cache/go-build



      - name: Install dependencies
        working-directory: ./src/backend
        run: |
          go mod tidy
          go mod download

      - name: Set environment variables for Elasticsearch
        run: |
          echo "ES_HOST=localhost" >> $GITHUB_ENV
          echo "ES_USERNAME=elastic" >> $GITHUB_ENV
          echo "ES_PASSWORD=changeme" >> $GITHUB_ENV      

      - name: Run tests
        working-directory: ./src/backend
        run: go test -v ./...

      - name: Build application
        working-directory: ./src/backend
        run: go build -v .

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf
        with:
          dockerfile: Dockerfile

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683

      - name: Set up Go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5
        with:
          go-version: 1.21

      - name: Clean Go cache
        run: |
          go clean -modcache
          rm -rf $GOPATH/pkg/mod
          rm -rf ~/.cache/go-build
      
      - name: golangci-lint
        uses: golangci/golangci-lint-action@4afd733a84b1f43292c63897423277bb7f4313a9
        with:
          version: latest
          working-directory: ./src/backend
          args: --timeout=5m